# Generated by Django 3.1.4 on 2021-02-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20210208_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default='Feb. 02,2021, 02:27 PM'),
        ),
    ]
