# Generated by Django 3.1.4 on 2021-02-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20210208_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.CharField(default='Feb. 02,2021, 02:29 PM', max_length=255),
        ),
    ]
